name: Maven Build Pipeline

on:
  push:
    branches: [main, dev, 'feature/**']
  pull_request:
    branches: [main, dev]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository'

jobs:
  setup:
    name: Determine Project Structure
    runs-on: self-hosted
    outputs:
      working-directory: ${{ steps.detect.outputs.working-directory }}
      java-version: ${{ steps.extract-java.outputs.java-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect project structure
        id: detect
        run: |
          if exist "pom.xml" (
            echo working-directory=. >> %GITHUB_OUTPUT%
            echo Maven project found in root directory
          ) else if exist "LRDMSimulator\pom.xml" (
            echo working-directory=LRDMSimulator >> %GITHUB_OUTPUT%
            echo Maven project found in LRDMSimulator subdirectory
          ) else (
            echo No Maven project found
            exit /b 1
          )
        shell: cmd

      - name: Extract Java version from POM
        id: extract-java
        run: |
          if exist "pom.xml" (
            set POM_PATH=pom.xml
          ) else (
            set POM_PATH=LRDMSimulator\pom.xml
          )
          
          REM Extract the actual version number from maven.compiler.source
          for /f "tokens=1,2 delims=<>" %%i in ('findstr "maven.compiler.source" %POM_PATH%') do (
            if "%%i"=="" (
              set EXTRACTED_VERSION=%%j
              goto :version_found
            )
          )
          
          :version_found
          if defined EXTRACTED_VERSION (
            echo java-version=%EXTRACTED_VERSION% >> %GITHUB_OUTPUT%
            echo Extracted Java version: %EXTRACTED_VERSION% from POM
          ) else (
            echo java-version=%JAVA_VERSION% >> %GITHUB_OUTPUT%
            echo Using default Java version: %JAVA_VERSION%
          )
        shell: cmd
        env:
          JAVA_VERSION: ${{ env.JAVA_VERSION }}

  build-main:
    name: Build Main Branch
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Fix Git permissions
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global core.autocrlf false
        shell: cmd

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ needs.setup.outputs.java-version }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            %USERPROFILE%\.m2\repository
            ${{ needs.setup.outputs.working-directory }}\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with coverage
        run: mvn clean verify -Pcoverage
        working-directory: ${{ needs.setup.outputs.working-directory }}
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: main-build-artifacts
          path: ${{ needs.setup.outputs.working-directory }}/target/

  build-dev:
    name: Build Dev Branch
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Fix Git permissions
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global core.autocrlf false
        shell: cmd

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ needs.setup.outputs.java-version }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            %USERPROFILE%\.m2\repository
            ${{ needs.setup.outputs.working-directory }}\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build without tests
        run: mvn clean compile test-compile -DskipTests=true
        working-directory: ${{ needs.setup.outputs.working-directory }}
        shell: cmd

  build-feature:
    name: Build Feature Branch
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Fix Git permissions
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global core.autocrlf false
        shell: cmd

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ needs.setup.outputs.java-version }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            %USERPROFILE%\.m2\repository
            ${{ needs.setup.outputs.working-directory }}\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Lightweight build
        run: mvn clean compile -DskipTests=true
        working-directory: ${{ needs.setup.outputs.working-directory }}
        shell: cmd

  build-pr:
    name: Build Pull Request
    if: github.event_name == 'pull_request'
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Fix Git permissions
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global core.autocrlf false
        shell: cmd

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ needs.setup.outputs.java-version }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            %USERPROFILE%\.m2\repository
            ${{ needs.setup.outputs.working-directory }}\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build and test PR
        run: mvn clean verify -Pcoverage
        working-directory: ${{ needs.setup.outputs.working-directory }}
        shell: cmd

      - name: Upload PR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pr-build-artifacts
          path: ${{ needs.setup.outputs.working-directory }}/target/
