name: SonarCloud Analysis Pipeline

on:
  workflow_run:
    workflows: ["Maven Build Pipeline"]
    types: [completed]
    branches: [main, dev, 'feature/**']
  pull_request:
    branches: [main, dev]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  SONAR_PROJECT_KEY: 'BenniProbst_LRDMSimulator'
  SONAR_ORGANIZATION: 'benniprobst'
  SONAR_HOST_URL: 'https://sonarcloud.io'
  WORKING_DIRECTORY: '.'

jobs:
  sonar-main:
    name: SonarCloud Main Analysis
    if: github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted
    steps:
      - name: Fix Git permissions
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global core.autocrlf false
        shell: cmd
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: main-build-artifacts
          path: target/
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Verify working directory
        run: |
          echo Current directory: %CD%
          echo Working directory will be: ${{ env.WORKING_DIRECTORY }}
          if exist pom.xml (
            echo Maven project found in current directory
          ) else (
            echo No Maven project found in current directory
            dir
          )
        shell: cmd
      - name: SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
        run: |
          mvn sonar:sonar ^
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} ^
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} ^
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} ^
            -Dsonar.token=${{ secrets.SONAR_SECRET }} ^
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        shell: cmd

  sonar-branches:
    name: SonarCloud Branch Analysis
    if: (github.event.workflow_run.head_branch == 'dev' || startsWith(github.event.workflow_run.head_branch, 'feature/')) && github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted
    steps:
      - name: Fix Git permissions
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global core.autocrlf false
        shell: cmd
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Verify working directory
        run: |
          echo Current directory: %CD%
          echo Working directory will be: ${{ env.WORKING_DIRECTORY }}
          if exist pom.xml (
            echo Maven project found in current directory
          ) else (
            echo No Maven project found in current directory
            dir
          )
        shell: cmd
      - name: SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
        run: |
          mvn sonar:sonar ^
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} ^
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} ^
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} ^
            -Dsonar.token=${{ secrets.SONAR_SECRET }} ^
            -DskipTests=true
        working-directory: ${{ env.WORKING_DIRECTORY }}
        shell: cmd

  sonar-pr:
    name: SonarCloud PR Analysis
    if: github.event_name == 'pull_request'
    runs-on: self-hosted
    steps:
      - name: Fix Git permissions
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global core.autocrlf false
        shell: cmd
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            .m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Verify working directory
        run: |
          echo Current directory: %CD%
          echo Working directory will be: ${{ env.WORKING_DIRECTORY }}
          if exist pom.xml (
            echo Maven project found in current directory
          ) else (
            echo No Maven project found in current directory
            dir
          )
        shell: cmd
      - name: Build and test for PR
        run: mvn clean verify -Pcoverage
        working-directory: ${{ env.WORKING_DIRECTORY }}
        shell: cmd
      - name: SonarCloud PR Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
        run: |
          mvn sonar:sonar ^
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} ^
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} ^
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} ^
            -Dsonar.token=${{ secrets.SONAR_SECRET }} ^
            -Dsonar.pullrequest.key=${{ github.event.number }} ^
            -Dsonar.pullrequest.branch=${{ github.head_ref }} ^
            -Dsonar.pullrequest.base=${{ github.base_ref }} ^
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        shell: cmd

  attestation:
    name: Attest SonarCloud Analysis Results
    if: always() && (needs.sonar-main.result == 'success' || needs.sonar-branches.result == 'success' || needs.sonar-pr.result == 'success')
    runs-on: self-hosted
    needs: [sonar-main, sonar-branches, sonar-pr]
    env:
      ARTIFACTS_DIR: ./sonar-artifacts
      REPORT_FILE: ./sonar-artifacts/analysis-report.txt
    steps:
      - name: Configure Git Environment
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global core.autocrlf false
        shell: cmd
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare Artifacts Directory
        run: if not exist "${{ env.ARTIFACTS_DIR }}" mkdir "${{ env.ARTIFACTS_DIR }}"
        shell: cmd
      - name: Generate Analysis Report
        run: |
          echo SonarCloud Analysis Report > "${{ env.REPORT_FILE }}"
          echo ========================== >> "${{ env.REPORT_FILE }}"
          echo Project: ${{ env.SONAR_PROJECT_KEY }} >> "${{ env.REPORT_FILE }}"
          echo Analysis Date: %DATE% %TIME% >> "${{ env.REPORT_FILE }}"
          echo SonarCloud URL: ${{ env.SONAR_HOST_URL }} >> "${{ env.REPORT_FILE }}"
          echo Organization: ${{ env.SONAR_ORGANIZATION }} >> "${{ env.REPORT_FILE }}"
          echo Workflow: ${{ github.workflow }} >> "${{ env.REPORT_FILE }}"
          echo Run ID: ${{ github.run_id }} >> "${{ env.REPORT_FILE }}"
        shell: cmd
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ env.ARTIFACTS_DIR }}/*'
