name: SonarCloud Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix Git permissions
        shell: cmd
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global core.autocrlf false

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: %USERPROFILE%\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: %USERPROFILE%\.sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and test with coverage
        shell: cmd
        run: mvn clean verify -Pcoverage

      - name: Debug - Check build artifacts
        shell: cmd
        run: |
          echo === Build artifacts ===
          if exist "target\classes" (
            echo Classes directory exists
            dir target\classes /s
          ) else (
            echo Classes directory missing
          )
          if exist "target\site\jacoco\jacoco.xml" (
            echo Coverage report found
          ) else (
            echo Coverage report missing
          )

      - name: Run SonarCloud analysis for Pull Request
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
        shell: cmd
        run: |
          mvn sonar:sonar ^
            -Dsonar.projectKey=BenniProbst_LRDMSimulator ^
            -Dsonar.organization=benniprobst ^
            -Dsonar.host.url=https://sonarcloud.io ^
            -Dsonar.sources=src ^
            -Dsonar.tests=tests ^
            -Dsonar.java.binaries=target/classes ^
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml ^
            -Dsonar.pullrequest.key=${{ github.event.number }} ^
            -Dsonar.pullrequest.branch=${{ github.head_ref }} ^
            -Dsonar.pullrequest.base=${{ github.base_ref }}

      - name: Run SonarCloud analysis for Main Branch
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
        shell: cmd
        run: |
          mvn sonar:sonar ^
            -Dsonar.projectKey=BenniProbst_LRDMSimulator ^
            -Dsonar.organization=benniprobst ^
            -Dsonar.host.url=https://sonarcloud.io ^
            -Dsonar.sources=src ^
            -Dsonar.tests=tests ^
            -Dsonar.java.binaries=target/classes ^
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
